name: Lint
on:
  push:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn format:check
